<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251220174031 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE abonnement (id INT AUTO_INCREMENT NOT NULL, module_abonnement_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, etat VARCHAR(255) NOT NULL, date_fin DATETIME NOT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_351268BBA20C84BB (module_abonnement_id), INDEX IDX_351268BBA4AEAFEA (entreprise_id), INDEX IDX_351268BBB03A8386 (created_by_id), INDEX IDX_351268BB896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE boutique (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, contact VARCHAR(255) NOT NULL, situation VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_A1223C54A4AEAFEA (entreprise_id), INDEX IDX_A1223C54B03A8386 (created_by_id), INDEX IDX_A1223C54896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE caisse (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, montant VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_B2A353C8A4AEAFEA (entreprise_id), INDEX IDX_B2A353C8B03A8386 (created_by_id), INDEX IDX_B2A353C8896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE caisse_boutique (id INT NOT NULL, boutique_id INT DEFAULT NULL, INDEX IDX_761557CCAB677BE6 (boutique_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE caisse_succursale (id INT NOT NULL, succursale_id INT DEFAULT NULL, INDEX IDX_DFF07E66C4166807 (succursale_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categorie_mesure (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_D93DC449A4AEAFEA (entreprise_id), INDEX IDX_D93DC449B03A8386 (created_by_id), INDEX IDX_D93DC449896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE categorie_type_mesure (id INT AUTO_INCREMENT NOT NULL, type_mesure_id INT DEFAULT NULL, categorie_mesure_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_A3322341F76D63EA (type_mesure_id), INDEX IDX_A3322341EEF42DFD (categorie_mesure_id), INDEX IDX_A3322341A4AEAFEA (entreprise_id), INDEX IDX_A3322341B03A8386 (created_by_id), INDEX IDX_A3322341896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE client (id INT AUTO_INCREMENT NOT NULL, surccursale_id INT DEFAULT NULL, photo_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, numero VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, prenom VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_C7440455F55AE19E (numero), INDEX IDX_C744045558AAF78E (surccursale_id), INDEX IDX_C74404557E9E4C8C (photo_id), INDEX IDX_C7440455AB677BE6 (boutique_id), INDEX IDX_C7440455A4AEAFEA (entreprise_id), INDEX IDX_C7440455B03A8386 (created_by_id), INDEX IDX_C7440455896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entre_stock (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, date DATETIME DEFAULT NULL, quantite INT NOT NULL, type VARCHAR(255) NOT NULL, statut VARCHAR(50) DEFAULT \'EN_ATTENTE\', commentaire LONGTEXT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_6F52C37CA4AEAFEA (entreprise_id), INDEX IDX_6F52C37CAB677BE6 (boutique_id), INDEX IDX_6F52C37CB03A8386 (created_by_id), INDEX IDX_6F52C37C896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise (id INT AUTO_INCREMENT NOT NULL, logo_id INT DEFAULT NULL, pays_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) DEFAULT NULL, numero VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_D19FA60F98F144A (logo_id), INDEX IDX_D19FA60A6E44244 (pays_id), INDEX IDX_D19FA60B03A8386 (created_by_id), INDEX IDX_D19FA60896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE facture (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, signature_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, succursale_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, date_retrait DATETIME NOT NULL, date_depot DATETIME NOT NULL, avance VARCHAR(255) DEFAULT NULL, montant_total VARCHAR(255) DEFAULT NULL, remise VARCHAR(255) DEFAULT NULL, reste_argent VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_FE86641019EB6921 (client_id), INDEX IDX_FE866410ED61183A (signature_id), INDEX IDX_FE866410A4AEAFEA (entreprise_id), INDEX IDX_FE866410C4166807 (succursale_id), INDEX IDX_FE866410B03A8386 (created_by_id), INDEX IDX_FE866410896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_entre (id INT AUTO_INCREMENT NOT NULL, modele_id INT DEFAULT NULL, entre_stock_id INT DEFAULT NULL, quantite INT NOT NULL, INDEX IDX_3C8C2B0FAC14B70A (modele_id), INDEX IDX_3C8C2B0F5E18E03E (entre_stock_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_mesure (id INT AUTO_INCREMENT NOT NULL, categorie_mesure_id INT DEFAULT NULL, mesure_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, taille VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_79C1F236EEF42DFD (categorie_mesure_id), INDEX IDX_79C1F23643AB22FA (mesure_id), INDEX IDX_79C1F236B03A8386 (created_by_id), INDEX IDX_79C1F236896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_module (id INT AUTO_INCREMENT NOT NULL, module_abonnement_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, quantite VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_2AFEBA6EA20C84BB (module_abonnement_id), INDEX IDX_2AFEBA6EB03A8386 (created_by_id), INDEX IDX_2AFEBA6E896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ligne_reservation (id INT AUTO_INCREMENT NOT NULL, reservation_id INT DEFAULT NULL, modele_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, quantite INT NOT NULL, avance_modele VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_212D8962B83297E7 (reservation_id), INDEX IDX_212D8962AC14B70A (modele_id), INDEX IDX_212D8962B03A8386 (created_by_id), INDEX IDX_212D8962896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mesure (id INT AUTO_INCREMENT NOT NULL, facture_id INT DEFAULT NULL, photo_modele_id INT DEFAULT NULL, photo_pagne_id INT DEFAULT NULL, type_mesure_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, montant VARCHAR(255) DEFAULT NULL, remise VARCHAR(255) DEFAULT NULL, etat VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_5F1B6E707F2DEE08 (facture_id), INDEX IDX_5F1B6E70A1EAE12B (photo_modele_id), INDEX IDX_5F1B6E70D184FBFF (photo_pagne_id), INDEX IDX_5F1B6E70F76D63EA (type_mesure_id), INDEX IDX_5F1B6E70B03A8386 (created_by_id), INDEX IDX_5F1B6E70896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modele (id INT AUTO_INCREMENT NOT NULL, photo_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, quantite_globale INT NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_100285587E9E4C8C (photo_id), INDEX IDX_10028558A4AEAFEA (entreprise_id), INDEX IDX_10028558B03A8386 (created_by_id), INDEX IDX_10028558896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modele_boutique (id INT AUTO_INCREMENT NOT NULL, modele_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, quantite INT NOT NULL, prix VARCHAR(255) NOT NULL, taille VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_C9FA0256AC14B70A (modele_id), INDEX IDX_C9FA0256AB677BE6 (boutique_id), INDEX IDX_C9FA0256B03A8386 (created_by_id), INDEX IDX_C9FA0256896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE module_abonnement (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, etat TINYINT(1) NOT NULL, description LONGTEXT NOT NULL, montant VARCHAR(255) NOT NULL, duree VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, numero INT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_A0F74326F55AE19E (numero), INDEX IDX_A0F74326B03A8386 (created_by_id), INDEX IDX_A0F74326896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, user_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, etat TINYINT(1) NOT NULL, titre VARCHAR(255) NOT NULL, libelle LONGTEXT NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_BF5476CAA4AEAFEA (entreprise_id), INDEX IDX_BF5476CAA76ED395 (user_id), INDEX IDX_BF5476CAB03A8386 (created_by_id), INDEX IDX_BF5476CA896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operateur (id INT AUTO_INCREMENT NOT NULL, pays_id INT DEFAULT NULL, photo_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, code VARCHAR(255) NOT NULL, libelle VARCHAR(255) NOT NULL, actif TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_B4B7F99DA6E44244 (pays_id), INDEX IDX_B4B7F99D7E9E4C8C (photo_id), INDEX IDX_B4B7F99DB03A8386 (created_by_id), INDEX IDX_B4B7F99D896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, montant VARCHAR(255) NOT NULL, reference VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_B1DC7A1EB03A8386 (created_by_id), INDEX IDX_B1DC7A1E896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement_abonnement (id INT NOT NULL, module_abonnement_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, channel VARCHAR(255) NOT NULL, state INT NOT NULL, pays VARCHAR(255) NOT NULL, data_user JSON NOT NULL, data_succursale JSON NOT NULL, data_boutique JSON NOT NULL, INDEX IDX_A3DD064BA20C84BB (module_abonnement_id), INDEX IDX_A3DD064BA4AEAFEA (entreprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement_boutique (id INT NOT NULL, boutique_id INT DEFAULT NULL, client_id INT DEFAULT NULL, quantite INT DEFAULT NULL, INDEX IDX_6B85C46EAB677BE6 (boutique_id), INDEX IDX_6B85C46E19EB6921 (client_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement_boutique_ligne (id INT AUTO_INCREMENT NOT NULL, modele_boutique_id INT DEFAULT NULL, paiement_boutique_id INT DEFAULT NULL, quantite INT DEFAULT NULL, montant VARCHAR(255) DEFAULT NULL, INDEX IDX_6DA675E6612EEE7B (modele_boutique_id), INDEX IDX_6DA675E6164C4694 (paiement_boutique_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE paiement_reservation (id INT NOT NULL, reservation_id INT DEFAULT NULL, INDEX IDX_FFE37427B83297E7 (reservation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE param_fichier (id INT AUTO_INCREMENT NOT NULL, size INT DEFAULT NULL, path VARCHAR(255) DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, date_creation DATETIME NOT NULL, url VARCHAR(5) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE pays (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, indicatif VARCHAR(255) NOT NULL, actif TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_349F3CAEB03A8386 (created_by_id), INDEX IDX_349F3CAE896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reservation (id INT AUTO_INCREMENT NOT NULL, client_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, montant VARCHAR(255) NOT NULL, date_retrait DATETIME DEFAULT NULL, avance VARCHAR(255) DEFAULT NULL, reste VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_42C8495519EB6921 (client_id), INDEX IDX_42C84955A4AEAFEA (entreprise_id), INDEX IDX_42C84955AB677BE6 (boutique_id), INDEX IDX_42C84955B03A8386 (created_by_id), INDEX IDX_42C84955896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_token (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, token VARCHAR(255) NOT NULL, expires_at DATETIME NOT NULL, UNIQUE INDEX UNIQ_452C9EC55F37A13B (token), INDEX IDX_452C9EC5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, nombre_user INT DEFAULT NULL, nombre_sms INT DEFAULT NULL, nombre_succursale INT NOT NULL, send_messsage_automatic_if_rendez_vous_proche TINYINT(1) DEFAULT NULL, nombre_jour_restant_pour_envoyer_sms INT DEFAULT NULL, modele_message_envoyer_pour_rendez_vous_proche LONGTEXT DEFAULT NULL, nombre_boutique INT NOT NULL, numero_abonnement INT DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_9F74B898A4AEAFEA (entreprise_id), INDEX IDX_9F74B898B03A8386 (created_by_id), INDEX IDX_9F74B898896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE surccursale (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, contact VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_3ABAE175A4AEAFEA (entreprise_id), INDEX IDX_3ABAE175B03A8386 (created_by_id), INDEX IDX_3ABAE175896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_mesure (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_7CCC0548A4AEAFEA (entreprise_id), INDEX IDX_7CCC0548B03A8386 (created_by_id), INDEX IDX_7CCC0548896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_user (id INT AUTO_INCREMENT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', is_active TINYINT(1) NOT NULL, INDEX IDX_5A9C1341B03A8386 (created_by_id), INDEX IDX_5A9C1341896DBBDE (updated_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE users (id INT AUTO_INCREMENT NOT NULL, surccursale_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, type_id INT DEFAULT NULL, logo_id INT DEFAULT NULL, boutique_id INT DEFAULT NULL, login VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active TINYINT(1) NOT NULL, created_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', nom VARCHAR(255) DEFAULT NULL, prenoms VARCHAR(255) DEFAULT NULL, plain_reset_token VARCHAR(6) DEFAULT NULL, plain_token_expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', fcm_token VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_1483A5E9AA08CB10 (login), INDEX IDX_1483A5E958AAF78E (surccursale_id), INDEX IDX_1483A5E9A4AEAFEA (entreprise_id), INDEX IDX_1483A5E9C54C8C93 (type_id), INDEX IDX_1483A5E9F98F144A (logo_id), INDEX IDX_1483A5E9AB677BE6 (boutique_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BBA20C84BB FOREIGN KEY (module_abonnement_id) REFERENCES module_abonnement (id)');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BBA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BBB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE boutique ADD CONSTRAINT FK_A1223C54A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE boutique ADD CONSTRAINT FK_A1223C54B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE boutique ADD CONSTRAINT FK_A1223C54896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE caisse ADD CONSTRAINT FK_B2A353C8A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE caisse ADD CONSTRAINT FK_B2A353C8B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE caisse ADD CONSTRAINT FK_B2A353C8896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE caisse_boutique ADD CONSTRAINT FK_761557CCAB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE caisse_boutique ADD CONSTRAINT FK_761557CCBF396750 FOREIGN KEY (id) REFERENCES caisse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE caisse_succursale ADD CONSTRAINT FK_DFF07E66C4166807 FOREIGN KEY (succursale_id) REFERENCES surccursale (id)');
        $this->addSql('ALTER TABLE caisse_succursale ADD CONSTRAINT FK_DFF07E66BF396750 FOREIGN KEY (id) REFERENCES caisse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE categorie_mesure ADD CONSTRAINT FK_D93DC449A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE categorie_mesure ADD CONSTRAINT FK_D93DC449B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE categorie_mesure ADD CONSTRAINT FK_D93DC449896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE categorie_type_mesure ADD CONSTRAINT FK_A3322341F76D63EA FOREIGN KEY (type_mesure_id) REFERENCES type_mesure (id)');
        $this->addSql('ALTER TABLE categorie_type_mesure ADD CONSTRAINT FK_A3322341EEF42DFD FOREIGN KEY (categorie_mesure_id) REFERENCES categorie_mesure (id)');
        $this->addSql('ALTER TABLE categorie_type_mesure ADD CONSTRAINT FK_A3322341A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE categorie_type_mesure ADD CONSTRAINT FK_A3322341B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE categorie_type_mesure ADD CONSTRAINT FK_A3322341896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C744045558AAF78E FOREIGN KEY (surccursale_id) REFERENCES surccursale (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C74404557E9E4C8C FOREIGN KEY (photo_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE client ADD CONSTRAINT FK_C7440455896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entre_stock ADD CONSTRAINT FK_6F52C37CA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE entre_stock ADD CONSTRAINT FK_6F52C37CAB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE entre_stock ADD CONSTRAINT FK_6F52C37CB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entre_stock ADD CONSTRAINT FK_6F52C37C896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60F98F144A FOREIGN KEY (logo_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60A6E44244 FOREIGN KEY (pays_id) REFERENCES pays (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA60896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641019EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410ED61183A FOREIGN KEY (signature_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410C4166807 FOREIGN KEY (succursale_id) REFERENCES surccursale (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ligne_entre ADD CONSTRAINT FK_3C8C2B0FAC14B70A FOREIGN KEY (modele_id) REFERENCES modele_boutique (id)');
        $this->addSql('ALTER TABLE ligne_entre ADD CONSTRAINT FK_3C8C2B0F5E18E03E FOREIGN KEY (entre_stock_id) REFERENCES entre_stock (id)');
        $this->addSql('ALTER TABLE ligne_mesure ADD CONSTRAINT FK_79C1F236EEF42DFD FOREIGN KEY (categorie_mesure_id) REFERENCES categorie_mesure (id)');
        $this->addSql('ALTER TABLE ligne_mesure ADD CONSTRAINT FK_79C1F23643AB22FA FOREIGN KEY (mesure_id) REFERENCES mesure (id)');
        $this->addSql('ALTER TABLE ligne_mesure ADD CONSTRAINT FK_79C1F236B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ligne_mesure ADD CONSTRAINT FK_79C1F236896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ligne_module ADD CONSTRAINT FK_2AFEBA6EA20C84BB FOREIGN KEY (module_abonnement_id) REFERENCES module_abonnement (id)');
        $this->addSql('ALTER TABLE ligne_module ADD CONSTRAINT FK_2AFEBA6EB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ligne_module ADD CONSTRAINT FK_2AFEBA6E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ligne_reservation ADD CONSTRAINT FK_212D8962B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id)');
        $this->addSql('ALTER TABLE ligne_reservation ADD CONSTRAINT FK_212D8962AC14B70A FOREIGN KEY (modele_id) REFERENCES modele_boutique (id)');
        $this->addSql('ALTER TABLE ligne_reservation ADD CONSTRAINT FK_212D8962B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE ligne_reservation ADD CONSTRAINT FK_212D8962896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE mesure ADD CONSTRAINT FK_5F1B6E707F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE mesure ADD CONSTRAINT FK_5F1B6E70A1EAE12B FOREIGN KEY (photo_modele_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE mesure ADD CONSTRAINT FK_5F1B6E70D184FBFF FOREIGN KEY (photo_pagne_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE mesure ADD CONSTRAINT FK_5F1B6E70F76D63EA FOREIGN KEY (type_mesure_id) REFERENCES type_mesure (id)');
        $this->addSql('ALTER TABLE mesure ADD CONSTRAINT FK_5F1B6E70B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE mesure ADD CONSTRAINT FK_5F1B6E70896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE modele ADD CONSTRAINT FK_100285587E9E4C8C FOREIGN KEY (photo_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE modele ADD CONSTRAINT FK_10028558A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE modele ADD CONSTRAINT FK_10028558B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE modele ADD CONSTRAINT FK_10028558896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE modele_boutique ADD CONSTRAINT FK_C9FA0256AC14B70A FOREIGN KEY (modele_id) REFERENCES modele (id)');
        $this->addSql('ALTER TABLE modele_boutique ADD CONSTRAINT FK_C9FA0256AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE modele_boutique ADD CONSTRAINT FK_C9FA0256B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE modele_boutique ADD CONSTRAINT FK_C9FA0256896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE module_abonnement ADD CONSTRAINT FK_A0F74326B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE module_abonnement ADD CONSTRAINT FK_A0F74326896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE operateur ADD CONSTRAINT FK_B4B7F99DA6E44244 FOREIGN KEY (pays_id) REFERENCES pays (id)');
        $this->addSql('ALTER TABLE operateur ADD CONSTRAINT FK_B4B7F99D7E9E4C8C FOREIGN KEY (photo_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE operateur ADD CONSTRAINT FK_B4B7F99DB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE operateur ADD CONSTRAINT FK_B4B7F99D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1EB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE paiement_abonnement ADD CONSTRAINT FK_A3DD064BA20C84BB FOREIGN KEY (module_abonnement_id) REFERENCES module_abonnement (id)');
        $this->addSql('ALTER TABLE paiement_abonnement ADD CONSTRAINT FK_A3DD064BA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE paiement_abonnement ADD CONSTRAINT FK_A3DD064BBF396750 FOREIGN KEY (id) REFERENCES paiement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paiement_boutique ADD CONSTRAINT FK_6B85C46EAB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE paiement_boutique ADD CONSTRAINT FK_6B85C46E19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE paiement_boutique ADD CONSTRAINT FK_6B85C46EBF396750 FOREIGN KEY (id) REFERENCES paiement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paiement_boutique_ligne ADD CONSTRAINT FK_6DA675E6612EEE7B FOREIGN KEY (modele_boutique_id) REFERENCES modele_boutique (id)');
        $this->addSql('ALTER TABLE paiement_boutique_ligne ADD CONSTRAINT FK_6DA675E6164C4694 FOREIGN KEY (paiement_boutique_id) REFERENCES paiement_boutique (id)');
        $this->addSql('ALTER TABLE paiement_reservation ADD CONSTRAINT FK_FFE37427B83297E7 FOREIGN KEY (reservation_id) REFERENCES reservation (id)');
        $this->addSql('ALTER TABLE paiement_reservation ADD CONSTRAINT FK_FFE37427BF396750 FOREIGN KEY (id) REFERENCES paiement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pays ADD CONSTRAINT FK_349F3CAEB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE pays ADD CONSTRAINT FK_349F3CAE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C8495519EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reservation ADD CONSTRAINT FK_42C84955896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE reset_password_token ADD CONSTRAINT FK_452C9EC5A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE setting ADD CONSTRAINT FK_9F74B898896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE surccursale ADD CONSTRAINT FK_3ABAE175A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE surccursale ADD CONSTRAINT FK_3ABAE175B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE surccursale ADD CONSTRAINT FK_3ABAE175896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE type_mesure ADD CONSTRAINT FK_7CCC0548A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE type_mesure ADD CONSTRAINT FK_7CCC0548B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE type_mesure ADD CONSTRAINT FK_7CCC0548896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE type_user ADD CONSTRAINT FK_5A9C1341B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE type_user ADD CONSTRAINT FK_5A9C1341896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E958AAF78E FOREIGN KEY (surccursale_id) REFERENCES surccursale (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9C54C8C93 FOREIGN KEY (type_id) REFERENCES type_user (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9F98F144A FOREIGN KEY (logo_id) REFERENCES param_fichier (id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9AB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE ligne_vente ADD CONSTRAINT FK_8B26C07C7DC7170A FOREIGN KEY (vente_id) REFERENCES vente (id)');
        $this->addSql('ALTER TABLE ligne_vente RENAME INDEX idx_3170b74b7dc7170a TO IDX_8B26C07C7DC7170A');
        $this->addSql('ALTER TABLE paiement_facture DROP date, DROP montant, DROP mode_paiement, DROP reference, CHANGE id id INT NOT NULL, CHANGE facture_id facture_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE paiement_facture ADD CONSTRAINT FK_E3BCD4E17F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('ALTER TABLE paiement_facture ADD CONSTRAINT FK_E3BCD4E1BF396750 FOREIGN KEY (id) REFERENCES paiement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE paiement_facture RENAME INDEX idx_f4e9a0477f2dee08 TO IDX_E3BCD4E17F2DEE08');
        $this->addSql('ALTER TABLE vente ADD CONSTRAINT FK_888A2A4CAB677BE6 FOREIGN KEY (boutique_id) REFERENCES boutique (id)');
        $this->addSql('ALTER TABLE vente ADD CONSTRAINT FK_888A2A4C19EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE vente RENAME INDEX idx_888a2a4cab677312 TO IDX_888A2A4CAB677BE6');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE vente DROP FOREIGN KEY FK_888A2A4CAB677BE6');
        $this->addSql('ALTER TABLE vente DROP FOREIGN KEY FK_888A2A4C19EB6921');
        $this->addSql('ALTER TABLE paiement_facture DROP FOREIGN KEY FK_E3BCD4E17F2DEE08');
        $this->addSql('ALTER TABLE paiement_facture DROP FOREIGN KEY FK_E3BCD4E1BF396750');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BBA20C84BB');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BBA4AEAFEA');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BBB03A8386');
        $this->addSql('ALTER TABLE abonnement DROP FOREIGN KEY FK_351268BB896DBBDE');
        $this->addSql('ALTER TABLE boutique DROP FOREIGN KEY FK_A1223C54A4AEAFEA');
        $this->addSql('ALTER TABLE boutique DROP FOREIGN KEY FK_A1223C54B03A8386');
        $this->addSql('ALTER TABLE boutique DROP FOREIGN KEY FK_A1223C54896DBBDE');
        $this->addSql('ALTER TABLE caisse DROP FOREIGN KEY FK_B2A353C8A4AEAFEA');
        $this->addSql('ALTER TABLE caisse DROP FOREIGN KEY FK_B2A353C8B03A8386');
        $this->addSql('ALTER TABLE caisse DROP FOREIGN KEY FK_B2A353C8896DBBDE');
        $this->addSql('ALTER TABLE caisse_boutique DROP FOREIGN KEY FK_761557CCAB677BE6');
        $this->addSql('ALTER TABLE caisse_boutique DROP FOREIGN KEY FK_761557CCBF396750');
        $this->addSql('ALTER TABLE caisse_succursale DROP FOREIGN KEY FK_DFF07E66C4166807');
        $this->addSql('ALTER TABLE caisse_succursale DROP FOREIGN KEY FK_DFF07E66BF396750');
        $this->addSql('ALTER TABLE categorie_mesure DROP FOREIGN KEY FK_D93DC449A4AEAFEA');
        $this->addSql('ALTER TABLE categorie_mesure DROP FOREIGN KEY FK_D93DC449B03A8386');
        $this->addSql('ALTER TABLE categorie_mesure DROP FOREIGN KEY FK_D93DC449896DBBDE');
        $this->addSql('ALTER TABLE categorie_type_mesure DROP FOREIGN KEY FK_A3322341F76D63EA');
        $this->addSql('ALTER TABLE categorie_type_mesure DROP FOREIGN KEY FK_A3322341EEF42DFD');
        $this->addSql('ALTER TABLE categorie_type_mesure DROP FOREIGN KEY FK_A3322341A4AEAFEA');
        $this->addSql('ALTER TABLE categorie_type_mesure DROP FOREIGN KEY FK_A3322341B03A8386');
        $this->addSql('ALTER TABLE categorie_type_mesure DROP FOREIGN KEY FK_A3322341896DBBDE');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C744045558AAF78E');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C74404557E9E4C8C');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455AB677BE6');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455A4AEAFEA');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455B03A8386');
        $this->addSql('ALTER TABLE client DROP FOREIGN KEY FK_C7440455896DBBDE');
        $this->addSql('ALTER TABLE entre_stock DROP FOREIGN KEY FK_6F52C37CA4AEAFEA');
        $this->addSql('ALTER TABLE entre_stock DROP FOREIGN KEY FK_6F52C37CAB677BE6');
        $this->addSql('ALTER TABLE entre_stock DROP FOREIGN KEY FK_6F52C37CB03A8386');
        $this->addSql('ALTER TABLE entre_stock DROP FOREIGN KEY FK_6F52C37C896DBBDE');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60F98F144A');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60A6E44244');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60B03A8386');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA60896DBBDE');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE86641019EB6921');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410ED61183A');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410A4AEAFEA');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410C4166807');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410B03A8386');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY FK_FE866410896DBBDE');
        $this->addSql('ALTER TABLE ligne_entre DROP FOREIGN KEY FK_3C8C2B0FAC14B70A');
        $this->addSql('ALTER TABLE ligne_entre DROP FOREIGN KEY FK_3C8C2B0F5E18E03E');
        $this->addSql('ALTER TABLE ligne_mesure DROP FOREIGN KEY FK_79C1F236EEF42DFD');
        $this->addSql('ALTER TABLE ligne_mesure DROP FOREIGN KEY FK_79C1F23643AB22FA');
        $this->addSql('ALTER TABLE ligne_mesure DROP FOREIGN KEY FK_79C1F236B03A8386');
        $this->addSql('ALTER TABLE ligne_mesure DROP FOREIGN KEY FK_79C1F236896DBBDE');
        $this->addSql('ALTER TABLE ligne_module DROP FOREIGN KEY FK_2AFEBA6EA20C84BB');
        $this->addSql('ALTER TABLE ligne_module DROP FOREIGN KEY FK_2AFEBA6EB03A8386');
        $this->addSql('ALTER TABLE ligne_module DROP FOREIGN KEY FK_2AFEBA6E896DBBDE');
        $this->addSql('ALTER TABLE ligne_reservation DROP FOREIGN KEY FK_212D8962B83297E7');
        $this->addSql('ALTER TABLE ligne_reservation DROP FOREIGN KEY FK_212D8962AC14B70A');
        $this->addSql('ALTER TABLE ligne_reservation DROP FOREIGN KEY FK_212D8962B03A8386');
        $this->addSql('ALTER TABLE ligne_reservation DROP FOREIGN KEY FK_212D8962896DBBDE');
        $this->addSql('ALTER TABLE mesure DROP FOREIGN KEY FK_5F1B6E707F2DEE08');
        $this->addSql('ALTER TABLE mesure DROP FOREIGN KEY FK_5F1B6E70A1EAE12B');
        $this->addSql('ALTER TABLE mesure DROP FOREIGN KEY FK_5F1B6E70D184FBFF');
        $this->addSql('ALTER TABLE mesure DROP FOREIGN KEY FK_5F1B6E70F76D63EA');
        $this->addSql('ALTER TABLE mesure DROP FOREIGN KEY FK_5F1B6E70B03A8386');
        $this->addSql('ALTER TABLE mesure DROP FOREIGN KEY FK_5F1B6E70896DBBDE');
        $this->addSql('ALTER TABLE modele DROP FOREIGN KEY FK_100285587E9E4C8C');
        $this->addSql('ALTER TABLE modele DROP FOREIGN KEY FK_10028558A4AEAFEA');
        $this->addSql('ALTER TABLE modele DROP FOREIGN KEY FK_10028558B03A8386');
        $this->addSql('ALTER TABLE modele DROP FOREIGN KEY FK_10028558896DBBDE');
        $this->addSql('ALTER TABLE modele_boutique DROP FOREIGN KEY FK_C9FA0256AC14B70A');
        $this->addSql('ALTER TABLE modele_boutique DROP FOREIGN KEY FK_C9FA0256AB677BE6');
        $this->addSql('ALTER TABLE modele_boutique DROP FOREIGN KEY FK_C9FA0256B03A8386');
        $this->addSql('ALTER TABLE modele_boutique DROP FOREIGN KEY FK_C9FA0256896DBBDE');
        $this->addSql('ALTER TABLE module_abonnement DROP FOREIGN KEY FK_A0F74326B03A8386');
        $this->addSql('ALTER TABLE module_abonnement DROP FOREIGN KEY FK_A0F74326896DBBDE');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA4AEAFEA');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAB03A8386');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA896DBBDE');
        $this->addSql('ALTER TABLE operateur DROP FOREIGN KEY FK_B4B7F99DA6E44244');
        $this->addSql('ALTER TABLE operateur DROP FOREIGN KEY FK_B4B7F99D7E9E4C8C');
        $this->addSql('ALTER TABLE operateur DROP FOREIGN KEY FK_B4B7F99DB03A8386');
        $this->addSql('ALTER TABLE operateur DROP FOREIGN KEY FK_B4B7F99D896DBBDE');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1EB03A8386');
        $this->addSql('ALTER TABLE paiement DROP FOREIGN KEY FK_B1DC7A1E896DBBDE');
        $this->addSql('ALTER TABLE paiement_abonnement DROP FOREIGN KEY FK_A3DD064BA20C84BB');
        $this->addSql('ALTER TABLE paiement_abonnement DROP FOREIGN KEY FK_A3DD064BA4AEAFEA');
        $this->addSql('ALTER TABLE paiement_abonnement DROP FOREIGN KEY FK_A3DD064BBF396750');
        $this->addSql('ALTER TABLE paiement_boutique DROP FOREIGN KEY FK_6B85C46EAB677BE6');
        $this->addSql('ALTER TABLE paiement_boutique DROP FOREIGN KEY FK_6B85C46E19EB6921');
        $this->addSql('ALTER TABLE paiement_boutique DROP FOREIGN KEY FK_6B85C46EBF396750');
        $this->addSql('ALTER TABLE paiement_boutique_ligne DROP FOREIGN KEY FK_6DA675E6612EEE7B');
        $this->addSql('ALTER TABLE paiement_boutique_ligne DROP FOREIGN KEY FK_6DA675E6164C4694');
        $this->addSql('ALTER TABLE paiement_reservation DROP FOREIGN KEY FK_FFE37427B83297E7');
        $this->addSql('ALTER TABLE paiement_reservation DROP FOREIGN KEY FK_FFE37427BF396750');
        $this->addSql('ALTER TABLE pays DROP FOREIGN KEY FK_349F3CAEB03A8386');
        $this->addSql('ALTER TABLE pays DROP FOREIGN KEY FK_349F3CAE896DBBDE');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C8495519EB6921');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955A4AEAFEA');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955AB677BE6');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955B03A8386');
        $this->addSql('ALTER TABLE reservation DROP FOREIGN KEY FK_42C84955896DBBDE');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE reset_password_token DROP FOREIGN KEY FK_452C9EC5A76ED395');
        $this->addSql('ALTER TABLE setting DROP FOREIGN KEY FK_9F74B898A4AEAFEA');
        $this->addSql('ALTER TABLE setting DROP FOREIGN KEY FK_9F74B898B03A8386');
        $this->addSql('ALTER TABLE setting DROP FOREIGN KEY FK_9F74B898896DBBDE');
        $this->addSql('ALTER TABLE surccursale DROP FOREIGN KEY FK_3ABAE175A4AEAFEA');
        $this->addSql('ALTER TABLE surccursale DROP FOREIGN KEY FK_3ABAE175B03A8386');
        $this->addSql('ALTER TABLE surccursale DROP FOREIGN KEY FK_3ABAE175896DBBDE');
        $this->addSql('ALTER TABLE type_mesure DROP FOREIGN KEY FK_7CCC0548A4AEAFEA');
        $this->addSql('ALTER TABLE type_mesure DROP FOREIGN KEY FK_7CCC0548B03A8386');
        $this->addSql('ALTER TABLE type_mesure DROP FOREIGN KEY FK_7CCC0548896DBBDE');
        $this->addSql('ALTER TABLE type_user DROP FOREIGN KEY FK_5A9C1341B03A8386');
        $this->addSql('ALTER TABLE type_user DROP FOREIGN KEY FK_5A9C1341896DBBDE');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E958AAF78E');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9A4AEAFEA');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9C54C8C93');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9F98F144A');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9AB677BE6');
        $this->addSql('DROP TABLE abonnement');
        $this->addSql('DROP TABLE boutique');
        $this->addSql('DROP TABLE caisse');
        $this->addSql('DROP TABLE caisse_boutique');
        $this->addSql('DROP TABLE caisse_succursale');
        $this->addSql('DROP TABLE categorie_mesure');
        $this->addSql('DROP TABLE categorie_type_mesure');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE entre_stock');
        $this->addSql('DROP TABLE entreprise');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE ligne_entre');
        $this->addSql('DROP TABLE ligne_mesure');
        $this->addSql('DROP TABLE ligne_module');
        $this->addSql('DROP TABLE ligne_reservation');
        $this->addSql('DROP TABLE mesure');
        $this->addSql('DROP TABLE modele');
        $this->addSql('DROP TABLE modele_boutique');
        $this->addSql('DROP TABLE module_abonnement');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE operateur');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE paiement_abonnement');
        $this->addSql('DROP TABLE paiement_boutique');
        $this->addSql('DROP TABLE paiement_boutique_ligne');
        $this->addSql('DROP TABLE paiement_reservation');
        $this->addSql('DROP TABLE param_fichier');
        $this->addSql('DROP TABLE pays');
        $this->addSql('DROP TABLE reservation');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE reset_password_token');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE surccursale');
        $this->addSql('DROP TABLE type_mesure');
        $this->addSql('DROP TABLE type_user');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE vente RENAME INDEX idx_888a2a4cab677be6 TO IDX_888A2A4CAB677312');
        $this->addSql('ALTER TABLE ligne_vente DROP FOREIGN KEY FK_8B26C07C7DC7170A');
        $this->addSql('ALTER TABLE ligne_vente RENAME INDEX idx_8b26c07c7dc7170a TO IDX_3170B74B7DC7170A');
        $this->addSql('ALTER TABLE paiement_facture ADD date DATETIME NOT NULL, ADD montant NUMERIC(10, 2) NOT NULL, ADD mode_paiement VARCHAR(50) DEFAULT NULL, ADD reference VARCHAR(100) DEFAULT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE facture_id facture_id INT NOT NULL');
        $this->addSql('ALTER TABLE paiement_facture RENAME INDEX idx_e3bcd4e17f2dee08 TO IDX_F4E9A0477F2DEE08');
    }
}
